source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
inhibit_all_warnings!

target 'VXRecognitionViewControllerDemo' do
  	# Comment the next line if you don't want to use dynamic frameworks
  	use_frameworks!

  	# Pods for VXRecognitionViewControllerDemo
	pod 'VXRecognitionViewController/Core', :path => '../../VXRecognitionViewController'
	pod 'Zip'
	
end
